/**
 * Prompt voice player — loads and plays TTS audio for question prompts.
 * Uses the manifest generated by edge-tts to map prompt text to audio files.
 */

import manifest from './promptManifest.json';

const CDN = 'https://gport.s3.eu-central-1.amazonaws.com/dreampick-tv';
let currentAudio = null;

export function playPromptVoice(promptText) {
  stopPromptVoice();

  const rawPath = manifest[promptText];
  if (!rawPath) return;

  const url = `${CDN}/${rawPath.replace(/^\//, '')}`;

  currentAudio = new Audio(url);
  currentAudio.volume = 0.8;
  currentAudio.play().catch(() => {
    // Autoplay blocked — ignore silently
  });
}

export function stopPromptVoice() {
  if (currentAudio) {
    currentAudio.pause();
    currentAudio.currentTime = 0;
    currentAudio = null;
  }
}
