/**
 * Prompt voice player — loads and plays TTS audio for question prompts.
 * Uses the manifest generated by edge-tts to map prompt text to audio files.
 */

import manifest from './promptManifest.json';

let currentAudio = null;

export function playPromptVoice(promptText) {
  stopPromptVoice();

  const path = manifest[promptText];
  if (!path) return;

  currentAudio = new Audio(path);
  currentAudio.volume = 0.8;
  currentAudio.play().catch(() => {
    // Autoplay blocked — ignore silently
  });
}

export function stopPromptVoice() {
  if (currentAudio) {
    currentAudio.pause();
    currentAudio.currentTime = 0;
    currentAudio = null;
  }
}
